//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentOfUser
    {
        public AppointmentOfUser()
        {
            this.AppointmentOfClinics = new HashSet<AppointmentOfClinic>();
        }
    
        public string ID { get; set; }
        public string IDUser { get; set; }
        public System.DateTime Appt { get; set; }
        public System.DateTime NextAppt { get; set; }
        public int NoDelay { get; set; }
    
        public virtual ICollection<AppointmentOfClinic> AppointmentOfClinics { get; set; }
        public virtual User User { get; set; }
    }
}
