//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUser
    {
        public GroupUser()
        {
            this.Users = new HashSet<User>();
        }
    
        public string IDGroup { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string IDClinic { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
