//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOfUser
    {
        public string ID { get; set; }
        public string IDUser { get; set; }
        public string NameUser { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public double CurrentPayment { get; set; }
        public System.DateTime NextPaymentDate { get; set; }
        public double NextPayment { get; set; }
        public int TimeLeft { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
