//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOfClinic
    {
        public string ID { get; set; }
        public string IDClinic { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public double Total_In { get; set; }
        public int NoComplete { get; set; }
        public int NoNotComplete { get; set; }
        public int NoDelay { get; set; }
    
        public virtual Clinic Clinic { get; set; }
    }
}
