//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AppointmentOfUsers = new HashSet<AppointmentOfUser>();
            this.Clinics = new HashSet<Clinic>();
            this.PaymentOfUsers = new HashSet<PaymentOfUser>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public string IDGroup { get; set; }
    
        public virtual ICollection<AppointmentOfUser> AppointmentOfUsers { get; set; }
        public virtual ICollection<Clinic> Clinics { get; set; }
        public virtual GroupUser GroupUser { get; set; }
        public virtual ICollection<PaymentOfUser> PaymentOfUsers { get; set; }
    }
}
