//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhongKhamEntities1 : DbContext
    {
        public QLPhongKhamEntities1()
            : base("name=QLPhongKhamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppointmentOfUser> AppointmentOfUsers { get; set; }
        public DbSet<Clinic> Clinics { get; set; }
        public DbSet<GroupUser> GroupUsers { get; set; }
        public DbSet<PaymentOfUser> PaymentOfUsers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<AppointmentOfClinic> AppointmentOfClinics { get; set; }
        public DbSet<PaymentOfClinic> PaymentOfClinics { get; set; }
    }
}
