//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuyVu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IDAppt { get; set; }
        public Nullable<int> NoOfTreatment { get; set; }
        public string IDPatient { get; set; }
        public Nullable<System.DateTime> DayOfTreatment { get; set; }
        public Nullable<System.DateTime> NextTreatmentDay { get; set; }
        public Nullable<int> NoOfDelay { get; set; }
        public Nullable<decimal> Mobile { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
