//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuyVu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApppointmentOfClinic
    {
        public int No_ { get; set; }
        public string IDPatient { get; set; }
        public string IDClinic { get; set; }
        public string IDAppt { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string NoOfAppt { get; set; }
        public string NoOfDelayAppt { get; set; }
        public decimal MobileOfDelayUser { get; set; }
    }
}
