//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuyVu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOfPatient
    {
        public int No_ { get; set; }
        public string IDPatient { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public double CurrentPayment { get; set; }
        public string TimeLeft { get; set; }
        public string IDStaff { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
